# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RN_59_10_QA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RN_59_10_QA
 pod 'TaboolaSDK', '2.5.0'

end
